version: "3.8"
services:
  db:
    image: postgres:16
    container_name: memoryseed-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: memoryseed
      POSTGRES_USER: ms-user
      POSTGRES_PASSWORD: memoryseeddb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
