spring:
  application:
    name: backend

  # ?????? ?? (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/memoryseed
    username: ms-user
    password: memoryseeddb
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Seoul

  # OAuth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(카카오)
            client-secret: ENC(카카오)
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
          google:
            client-id: ENC(구글)
            client-secret: ENC(구글)
            scope: profile, email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT 설정
jwt:
  secret: "MemorySeedProjectSecretKeyWhichIsVeryLongAndSecureForJwtTokenAuthentication123456789"
  # 토큰 만료 시간 (밀리초 단위, 86400000 = 24시간)
  expiration: 86400000

# ?? API (AccuWeather) ??
accuweather:
  base-url: https://dataservice.accuweather.com
  api-key: zpka_9225b9589f404a60b664d39031889e66_a7317a3b