spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/memoryseed
spring.datasource.username=ms-user
spring.datasource.password=memoryseeddb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

accuweather.base-url=https://dataservice.accuweather.com
accuweather.api-key=zpka_9225b9589f404a60b664d39031889e66_a7317a3b
